### ISSUE TITLE
bugs :)

### ISSUE THREAD

**Issue by SeKi81** [MiCode/miui_recovery#1]
this repo is incomplete

/system/ is empty.

I´ve built this recovery for HTC One S
- Its blue?! Screen is blue, everything is blue... 
- USB mount not working  This is a known bug from cwm: TWRP has a workaround for onex/ones:   https://github.com/TeamWin/device_htc_ville/commits/master

**Comment by dennise** [comment]
HTC One S has not been supported completely.Now the NS is only supported.Please wait for some weeks.
